# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json

# https://github.com/oapi-codegen/oapi-codegen
package: client
generate:
  models: true
  client: true
output: internal/client/archestra_client.go

output-options:
  exclude-tags:
    - LLM Proxy
    - Auth
    - MCP Gateway
    - Interaction
    - Health
    - A2A
    - Chat
    - ChatOps
    - ChatOps Webhooks
    - Config
    - Connectors
    - Incoming Email
    - Invitation
    - Knowledge Bases
    - LLM Models
    - MCP Tool Call
    - Member
    - Members
    - OAuth
    - Roles
    - Secrets
    - Statistics
    - User Tokens
    - Vault
    - Virtual API Keys
    - Webhooks
    - mcp-proxy
  exclude-schemas:
    - OpenAiChatCompletionRequest
    - OpenAiChatCompletionRequestInput
    - OpenAiChatCompletionResponse
    - OpenAiChatCompletionResponseInput
    - GeminiGenerateContentRequest
    - GeminiGenerateContentRequestInput
    - GeminiGenerateContentResponse
    - GeminiGenerateContentResponseInput
    - AnthropicMessagesRequest
    - AnthropicMessagesRequestInput
    - AnthropicMessagesResponse
    - AnthropicMessagesResponseInput
    - CerebrasChatCompletionRequest
    - CerebrasChatCompletionRequestInput
    - CerebrasChatCompletionResponse
    - CerebrasChatCompletionResponseInput
    - CohereChatRequest
    - CohereChatRequestInput
    - CohereChatResponse
    - CohereChatResponseInput
    - DeepSeekChatCompletionRequest
    - DeepSeekChatCompletionRequestInput
    - DeepSeekChatCompletionResponse
    - DeepSeekChatCompletionResponseInput
    - GroqChatCompletionRequest
    - GroqChatCompletionRequestInput
    - GroqChatCompletionResponse
    - GroqChatCompletionResponseInput
    - MinimaxChatCompletionRequest
    - MinimaxChatCompletionRequestInput
    - MinimaxChatCompletionResponse
    - MinimaxChatCompletionResponseInput
    - MistralChatCompletionRequest
    - MistralChatCompletionRequestInput
    - MistralChatCompletionResponse
    - MistralChatCompletionResponseInput
    - OllamaChatCompletionRequest
    - OllamaChatCompletionRequestInput
    - OllamaChatCompletionResponse
    - OllamaChatCompletionResponseInput
    - PerplexityChatCompletionRequest
    - PerplexityChatCompletionRequestInput
    - PerplexityChatCompletionResponse
    - PerplexityChatCompletionResponseInput
    - VllmChatCompletionRequest
    - VllmChatCompletionRequestInput
    - VllmChatCompletionResponse
    - VllmChatCompletionResponseInput
    - XaiChatCompletionRequest
    - XaiChatCompletionRequestInput
    - XaiChatCompletionResponse
    - XaiChatCompletionResponseInput
    - ZhipuaiChatCompletionRequest
    - ZhipuaiChatCompletionRequestInput
    - ZhipuaiChatCompletionResponse
    - ZhipuaiChatCompletionResponseInput
